### ISSUE TITLE
Change Cart order request format

### ISSUE THREAD

**Issue by ditinex** [ditinex/M-Sand-Bazar#3]
Change cart order axios request format
Provide the below details with same index name, price and delivery charge is for each item

            $productid = $this->value('productid');
            $name = $this->value('name');
            $address = $this->value('address');
            $dealerid = $this->value('dealerid');
            $status = $this->value('status');
            $price = $this->value('price');
            $deliverycharge = $this->value('deliverycharge');
            $userid = $this->value('userid');

**Comment by Souradeep-16** [comment]
@ditinex userid taking some garbage value .Need Correction!

**Comment by ditinex** [comment]
Send user id instead of phone number

**Comment by ditinex** [comment]
Fixed
