### ISSUE TITLE
Add forgot password API

### ISSUE THREAD

**Issue by ditinex** [ditinex/M-Sand-Bazar#4]
Add forgot password api

**Comment by ditinex** [comment]
API Added 

URL : /forgotpassword
METHOD : POST
DATA : phone, password

```
public function forgotPassword()
        {
            $this->checkRequestMethod('POST');
            $phone = $this->value('phone');
            $password = md5($this->value('password'));
          
            $query = $this->query("UPDATE `user` SET `password`='$password' WHERE `phone`='$phone'");
            $output["error"] = false;
        
            $this->returnOutput($output,true);
        }
```

**Comment by ditinex** [comment]
@Souradeep-16  Add forgot password functionality in app and close the issue

**Comment by Souradeep-16** [comment]
There is no option to check either the account is exist or not with the phone number provided

**Comment by Souradeep-16** [comment]
@ditinex  There is no option to check either the account is exist or not with the phone number provided

**Comment by Souradeep-16** [comment]
@ditinex implement this with php api

fetch('http://18.217.108.14:3784/sms', {
        method: 'POST',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: 'rotp',
          phone: phone,
          otps: ''
        })
      }).then((response) => response.json())
      .then((responseJson) => {

        //console.log(responseJson.otp);//If server response message same as Data Matched
        if (responseJson.code === 'success') {
          this.setState({
            otp: responseJson.otp,
            ready: true
          });
        } else {
            Alert.alert('Technical error !');
        }
      }).catch((error) => {
        console.error(error);
      });

**Comment by Souradeep-16** [comment]
forgot pass api returning false but pass not changed

**Comment by ditinex** [comment]
Account exists and forgot password fixed
