### ISSUE TITLE
orderlist api

### ISSUE THREAD

**Issue by Souradeep-16** [ditinex/M-Sand-Bazar#5]
Issue in orderlist api ...it is returning only one last item

**Comment by ditinex** [comment]
**Fixed and tested**

`
{
  "error": false,
  "data": [
    {
      "id": "3",
      "name": "Asif",
      "address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
      "productid": "2",
      "price": "1080",
      "deliverycharge": "100",
      "timestamp": "25/10/2019",
      "userid": "10",
      "dealerid": "2",
      "status": "Pending"
    },
    {
      "id": "4",
      "name": "Asif",
      "address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
      "productid": "3",
      "price": "700",
      "deliverycharge": "100",
      "timestamp": "25/10/2019",
      "userid": "10",
      "dealerid": "1",
      "status": "Pending"
    }
  ]
}
`

**Comment by souradeepdas16** [comment]
It is not big issue but if request to the api with no data then also its returning some values.........

**Comment by ditinex** [comment]
Fixed
