### ISSUE TITLE
Per dealer orderlist need where i will send the dealer id with api '/getdealerorderlist'

### ISSUE THREAD

**Issue by souradeepdas16** [ditinex/M-Sand-Bazar#6]

**Comment by ditinex** [comment]
**Added Feature**

URL : http://codeplay.site/ftp/ditinex/SandApi/getdealerorderlist
METHOD : POST
DATA : { 'id' : 1 }


Find the output snippet below :
`{
  "error": false,
  "data": [
    {
      "id": "15",
      "name": "Souradeep Das",
      "address": "119/1, Kadam Tala, Howrah, West Bengal 711101, India",
      "productid": "3",
      "price": "650",
      "quantity": "1",
      "deliverycharge": "50",
      "timestamp": "25/10/2019",
      "userid": "11",
      "dealerid": "1",
      "status": "Pending",
      "product_title": "Ultatech Cement"
    },
    {
      "id": "14",
      "name": "Souradeep Das",
      "address": "119/1, Kadam Tala, Howrah, West Bengal 711101, India",
      "productid": "5",
      "price": "550",
      "quantity": "3",
      "deliverycharge": "50",
      "timestamp": "25/10/2019",
      "userid": "11",
      "dealerid": "1",
      "status": "Pending",
      "product_title": "Ambuja Cement"
    },
    {
      "id": "4",
      "name": "Asif",
      "address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
      "productid": "3",
      "price": "700",
      "quantity": "0",
      "deliverycharge": "100",
      "timestamp": "25/10/2019",
      "userid": "10",
      "dealerid": "1",
      "status": "Pending",
      "product_title": "Ultatech Cement"
    }
  ]
}`
