### ISSUE TITLE
Need dynamic Product details changing api

### ISSUE THREAD

**Issue by Souradeep-16** [ditinex/M-Sand-Bazar#8]
i mean i api but i can change title price image anything with that

**Comment by ditinex** [comment]
API URL
'addproduct' => 'addProduct',
'editproduct' => 'editProduct',
'deleteproduct' => 'deleteProduct',

Add Product 
----------------
POST Method
$product_title = $this->value('product_title');
$product_price = $this->value('product_price');
$product_des = $this->value('product_des');
send image with field name : file


Edit Product 
----------------
POST Method
$product_id = $this->value('product_id');
$product_title = $this->value('product_title');
$product_price = $this->value('product_price');
$product_des = $this->value('product_des');
send image with field name : file

** don't send file field if image is not to be updated but all other fields are required. 


Delete product 
---------------------
$product_id = $this->value('product_id');

**Comment by souradeepdas16** [comment]
how can i send the new image or edit product image????

**Comment by ditinex** [comment]
POST Method
$product_id = $this->value('product_id');
$product_title = $this->value('product_title');
$product_price = $this->value('product_price');
$product_des = $this->value('product_des');
send image with field name : file

** don't send file field if image is not to be updated but all other fields are required.

**Comment by ditinex** [comment]
post method
