### ISSUE TITLE
dealer entry api need

### ISSUE THREAD

**Issue by Souradeep-16** [ditinex/M-Sand-Bazar#9]

**Comment by ditinex** [comment]
'createdealer' => 'createDealer',
	'editdealer' => 'editDealer',
	'deletedealer' => 'deleteDealer',

Create Dealer
-----------------
                $address = $this->value('address');
                $phone = $this->value('phone');
                $name = $this->value('name');
                $pass = md5($this->value('pass'));
                $latitude = $this->value('latitude');
                $longitude = $this->value('longitude');

Edit Dealer
--------------
                $id = $this->value('id');
                $address = $this->value('address');
                $phone = $this->value('phone');
                $name = $this->value('name');
                $pass = md5($this->value('pass'));
                $latitude = $this->value('latitude');
                $longitude = $this->value('longitude');

Delete Dealer
--------------
                $id = $this->value('id');
